### ISSUE TITLE
(🎁) generate Gradle tasks for additional source sets

### ISSUE THREAD

**Issue by KotlinIsland** [detekt/detekt#6796] opened 2024-01-03 00:32 UTC
This https://github.com/detekt/detekt/discussions/6758#discussioncomment-7945099

**Comment by 3flex** [comment] 2024-01-03 08:06
I consider this a duplicate of #6634, as the solution for that would create a task for each source set including any that are manually added.

**Closed by 3flex** 2024-01-03 08:06 UTC
Labels: feature
