### ISSUE TITLE
Allow usage of LibraryCodeMustSpecifyReturnType in non-explicit mode

### ISSUE THREAD

**Issue by hoanghun** [detekt/detekt#6225] opened 2023-06-16 09:17 UTC
## Expected Behavior of the rule
LibraryCodeMustSpecifyReturnType currently only works if explicit mode is on which is not something we want in our code base but we want to force return type on every method.

## Context
In this issue https://github.com/detekt/detekt/issues/5692 ExplicitlyDefineReturn was introduced but for some reason was not merged and instead a configuration flag was added to LibraryCodeMustSpecifyReturnType.

**Comment by cortinico** [comment] 2023-07-14 01:11
> LibraryCodeMustSpecifyReturnType currently only works if explicit mode is on which is not something we want in our code base but we want to force return type on every method.

This is not correct. Have you found this information online on our website?

**Comment by hoanghun** [comment] 2023-08-13 09:50
> > LibraryCodeMustSpecifyReturnType currently only works if explicit mode is on which is not something we want in our code base but we want to force return type on every method.
> 
> This is not correct. Have you found this information online on our website?

I have not found on the website, but I got LibraryCodeMustSpecifyReturnType warning only after I turned the explicit api mode on.

On the website, the Explicit api is referenced though.
<img width="852" alt="image" src="https://github.com/detekt/detekt/assets/17816312/b52fe815-8bd5-4510-9b3b-e1b8cbf7981f">

**Comment by BraisGabin** [comment] 2023-08-16 21:24
I reviewed the rule and I can't see anything that could explain what you are describing. Could you provide a simple project to reproduce this issue?

**Comment by cortinico** [comment] 2023-08-19 19:16
> should be marked with the `LibraryCodeMustSpecifyReturnType` warning since there is no return type, I get no warning from detekt unless I turn the explicit api mode on.

This rule uses type resolution, and is on an external ruleset. So you will have to run detekt using the `detektMain` task add the dependencies on the `-libraries` ruleset with the `detektPlugin(...)` dependency. Are you doing so? As I suspect that's the reason why you don't see this rule running.

**Comment by cortinico** [comment] 2023-10-21 14:56
> Are you doing so? As I suspect that's the reason why you don't see this rule running.

Closing as @hoanghun is unresponsive

**Closed by cortinico** 2023-10-21 14:56 UTC
Labels: rules, waiting for feedback
