### ISSUE TITLE
UnnecessaryAbstractClass title is too verbose

### ISSUE THREAD

**Issue by TWiStErRob** [detekt/detekt#4750] opened 2022-04-23 14:31 UTC
## Expected Behavior of the rule

UnnecessaryAbstractClass should have a concise description like other rules

## Context
I just updated Detekt 1.19.0 to 1.20.0 and got this failure:
https://github.com/TWiStErRob/net.twisterrob.cinema/security/code-scanning/227

The message is just plain weird to be this long:
![image](https://user-images.githubusercontent.com/2906988/164910306-4b4478c4-06c2-45f4-8b4d-132d11a76623.png)

detail screen:
![image](https://user-images.githubusercontent.com/2906988/164910247-930c8fdf-1dcd-40ad-9ae9-bd8268548bb9.png)

**Comment by TWiStErRob** [comment] 2022-04-23 14:32
I noticed MagicNumber to have the same problem, but many others look perfectly good. Should there be a check on how long the description can be? and/or introduce: "title" and "detail" descriptions?

**Comment by BraisGabin** [comment] 2022-04-24 14:56
I'm not sure if this issue is in the description or it is on our impregnation of Sarif where we are using the wrong description. The rules have 3 different descriptions: kdoc, description about the role and description about the issue. It seems that we use the second where we should use the third.

**Comment by TWiStErRob** [comment] 2022-04-24 22:06
So you're thinking about swapping the two? Because we need both, see the description on the line itself in the screenshots.

**Comment by BraisGabin** [comment] 2022-04-25 22:16
My bad, I dind't see the screenshots with detail. Yes, I agree that this description is long an it's not that useful. We should change it. We even have a style guide for this: https://github.com/detekt/detekt/blob/main/.github/CONTRIBUTING.md#rule-descriptions

**Comment by 3flex** [comment] 2022-04-26 08:43
Is this a dupe of #4163?

**Comment by BraisGabin** [comment] 2022-04-26 10:29
🤔 It is but I'm not sure which one I prefer. This issue is easily actionable. The bug is at `UnnecessaryAbstractClass`. The other is really generic and if no one is going to do the reseach to list all the rules that should be fixed I would vote to close it and fix the ones that are reported (or just send a PR if someone find an issue like this in other rule).

**Comment by 3flex** [comment] 2022-04-26 10:48
Makes sense, I'll close the other one

**Comment by TWiStErRob** [comment] 2022-04-26 19:51
I think this is more like a subtask of the other one.

**Comment by BraisGabin** [comment] 2022-04-28 07:16
Maybe, but this one is easily actionable and it's clear when it's done while the other is too broad. We prefer actionable issues because anyone can take them and send a PR to fix them. The broad issues are nearly always waiting for a maintainer to be implemented so they can take long time. For example, you can open a new issue to add a rule to check the lenght of the rule description. That's easily actionable. Then with that rule we can create another issue to fix all the issues that rule find.

**Comment by segunfamisa** [comment] 2022-08-12 07:17
Heya folks! I'm looking to get familiar with the project, so I'd love to take this if that's okay 😄

**Comment by 3flex** [comment] 2022-08-12 09:35
Please go ahead! And thank you for your help :)

**Closed** 2022-08-15 17:09 UTC
Labels: help wanted, rules, good first issue
