### ISSUE TITLE
The 'detekt' Gradle task does not do anything in Kotlin multi-platform projects

### ISSUE THREAD

**Issue by utybo** [detekt/detekt#3663] opened 2021-04-08 09:33 UTC
## Expected Behavior
 
Either launches detekt on the common sources or on everything.

## Observed Behavior

Does not do anything [(NO-SOURCE)](https://github.com/utybo/detekt-kotlin-mpp/runs/2295387305#step:4:28)

## Steps to Reproduce

* Use Kotlin MPP and Detekt
* Launch `gradle detekt` or `./gradlew detekt`

## Context

This is quite annoying for Kotlin MPP. A [repro repo (that also highlights other issues)](https://github.com/utybo/detekt-kotlin-mpp) is available. I encountered this while trying to set up Detekt for [one of my projects](https://github.com/utybo/Lixy).

A possible workaround is to manually configure the `detekt` task to give it the inputs we want.

## Your Environment

* Version of detekt used: 1.16.0
* Version of Gradle used (if applicable): 6.8.3
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/ijjvolhqcdvhk
* Operating System and version: Windows 10, 19043
* Link to your project (if it's a public repository): https://github.com/utybo/detekt-kotlin-mpp

**Comment by BraisGabin** [comment] 2021-04-08 15:59
the `detekt` task only checks code in `src/main/kotlin` and `src/main/java`. If you want it to check other folders you need to use the `input` configuration. 

#3649 will add `src/test/kotlin` and `src/test/java` as default folders too. But that will be introduced in the next release.

**Comment by petertrr** [comment] 2021-05-12 08:55
I can see that #3453 added support for multiplatform projects, but it creates only a set of independent tasks with names like `detekt<platform>Main`, `detekt<platform>Test`. For me it would seem logical, if `detekt` task will still be created and it would aggregate all individual platform tasks. Now these individual tasks are added as dependencies for `check` task, but it's not clear, how to run only detekt-related task. It can be simply implemented like
```kotlin
tasks.register("detektAll") {
        allprojects {
            this@register.dependsOn(tasks.withType<Detekt>())
        }
    }
```
but I think it's worth considering to make it default behavior.

**Comment by cortinico** [comment] 2021-05-12 09:08
That's the intended behavior

> For me it would seem logical, if `detekt` task will still be created and it would aggregate all individual platform tasks

The `detekt` ("plain") task is always running without type resolution enabled. 
See: https://detekt.github.io/detekt/type-resolution.html

So whenever you apply the Detekt Gradle plugin, a `detekt` task will be created that will check `src/main/kotlin` and `src/main/java` as @BraisGabin mentioned.

Moreover, if the plugin discovers that you're applying also other plugins, say KMM, AGP or so, we create additional tasks.

So for consistency and backward compat. reasons, I would not change the behavior of the `detekt` task

> but I think it's worth considering to make it default behavior.

I think we could add a `detektAll` task that can depend on all the `detekt*` tasks.

**Closed by cortinico** 2021-05-12 09:08 UTC

**Comment by petertrr** [comment] 2021-05-12 09:10
@cortinico thanks for the explanation!

**Comment by arkivanov** [comment] 2021-12-22 20:20
@cortinico Sorry for commenting on the closed issue, but this issue is still not clear for me. I have a KMP project and I have detekt enabled. When I run "gradlew build" task on Linux, detekt doesn't find issues in common code, and there is the following output in the console:

```
> Task :my-module:detekt NO-SOURCE
```

There are Gradle tasks for every target, like `detektLinuxX64Main`, `detektMetadataCommonMain`, etc. But seems like they are not executed if I just call `build`. How could I workaround this?

**Comment by petertrr** [comment] 2021-12-22 20:38
@arkivanov personally I use either this to always execute detekt tasks
```kotlin
tasks.withType<Detekt> {
    tasks.getByName("build").dependsOn(this)
}
```
or this to have a task to call them explicitly
```kotlin
tasks.register("detektAll") {
    allprojects {
        this@register.dependsOn(tasks.withType<Detekt>())
    }
}
```
But I too would be interested about an official recommendation on how to do this.

**Comment by arkivanov** [comment] 2021-12-23 20:34
@petertrr Thanks for the idea! I enabled tasks in a similar way and detekt found some issues in the existing code, because detekt was never actually executed.

**Comment by cortinico** [comment] 2022-01-02 20:38
> when I run "gradlew build" task on Linux, detekt doesn't find issues in common code, and there is the following output in the console:

Just to follow up here: what you're experiencing is the expected behavior. The Detekt Gradle Plugin adds a dependency between `check` and the `detekt` task **only** (not for all the other `detekt...Main` tasks). That's because those extra tasks are running with Type Resolution which would let you incur in a performance hit.

The solution suggested by @petertrr is the most idiomatic one you can follow up to adapt the behavior 👍

**Comment by arkivanov** [comment] 2022-01-02 21:02
@cortinico thanks for the clarification! However I find this confusing. This might be an expected behavior as well as an unexpected (e.g. my case). I was using Detekt for a year in my projects, and just recently realized that the type resolution was not ever enabled. As a result many issues were missed (fortunately not critical), and I had to fix them now. Maybe there could be a documented configuration flag?

**Comment by cortinico** [comment] 2022-01-02 21:08
Agree that this feature is not well advertised. We do have a page here: https://detekt.github.io/detekt/type-resolution.html

We also miss a `Enabling on an Multiplatform project` section over there.

> Maybe there could be a documented configuration flag?

Sadly there is no flag. This is probably a poor design choice on our end when this capability was initially designed. So far it was decided to offer different Gradle tasks to enable/disable this feature so that it could be fully isolated and you could run the two "modes" side by side.

**Comment by mecoFarid** [comment] 2025-05-28 18:09
BTW, solution suggested by @petertrr causes duplicated reports. Example: 
```

> Task :my:module:preferences:detektMetadataMain FAILED
/xxx/yyyy/PreferencesDataSource.kt:26:10: The caught exception is too generic. Prefer catching specific exceptions to the case that is currently handled. [TooGenericExceptionCaught]

> Task :my:module:preferences:detektMetadataCommonMain FAILED
/xxx/yyyy/PreferencesDataSource.kt:26:10: The caught exception is too generic. Prefer catching specific exceptions to the case that is currently handled. [TooGenericExceptionCaught]

```

**Comment by BraisGabin** [comment] 2025-06-09 15:50
If you want a good answer please open a new issue providing more information. Expected vs actual behaviour, etc. For context you can link this issue as many times as you want but thus issue is really old so probably a lot of things told here changed already.

For example, at that point KMP was not stable.
