### ISSUE TITLE
Robust asserts in rule tests

### ISSUE THREAD

**Issue by schalkms** [detekt/detekt#2087] opened 2019-11-15 19:05 UTC
- For each rule there should be at least one test case that asserts the violation message and the reported element (`KtElement').
- For each `report()` statement in the rule there should be one test case that asserts the violation message and the reported element (`KtElement').

**Comment by BraisGabin** [comment] 2019-11-16 12:22
I think that we should test the `TextLocation` or `SourceLocation` too. `TextLocation` is "better" because it checks the start and the end but `SourceLocation` is much easier to understand and mantain. So I think that we should test at least `SourceLocation`. And for the test that have sense test `TextLocation` instead.

On the other hand I don't understand why or how to test the `KtElement`. It's only used to check if a Finding is supressed or not.

**Comment by schalkms** [comment] 2019-11-16 18:10
That's also a very nice idea! This is exactly what's needed.

> On the other hand I don't understand why or how to test the KtElement. It's only used to check if a Finding is supressed or not.

Your referenced issue does exactly that. We check the `.text` or `.name` property of this reported `KtElement`.

**Comment by BraisGabin** [comment] 2019-11-17 01:14
#2013 introduced a change here. Now the psiElement that is used for the location may be different for the one that is stored in the ktElement. So it's safer to check the location than the ktElement.

**Comment by BraisGabin** [comment] 2019-11-17 01:18
Sorry, I miss read your comment. Forget what I said in my previous comment.

**Comment by cortinico** [comment] 2021-11-11 20:36
> I think that we should test the `TextLocation` or `SourceLocation` too. `TextLocation` is "better" because it checks the start and the end but `SourceLocation` is much easier to understand and mantain. So I think that we should test at least `SourceLocation`. And for the test that have sense test `TextLocation` instead.

We haven't done this recently for several rules. What's our take here? Imho:
- Assert `isEmpty` or `hasSize(1)` if there is just one inspection is sufficient.
- `TextLocation` or `SourceLocation` should be asserted for every `hasSize(x)` where `x>=2`

**Comment by BraisGabin** [comment] 2021-11-12 13:54
The problem here is that, sometimes, we don't test which `KtElement` we are reporting. And that value is important because it is used in several points down the road:

- Baseline
- Suppress
- Reporting

But force us to test the `KtElement` each time seems too much. So I'd say that we should add some of those and, if we find bugs or regressions add tests to ensure that it doesn't happen again.

**Comment by BraisGabin** [comment] 2021-12-26 19:04
There is nothing that we can do to say "this issue is done". This is just something that we should keep in mind while writting and reviewing tests.

For that reason, I'm closing this.

**Closed by BraisGabin** 2021-12-26 19:04 UTC
Labels: rules, test
