### ISSUE TITLE
Is where some examples or documentation about changing code?

### ISSUE THREAD

**Issue by comdiv** [detekt/detekt#3267] opened 2020-12-08 03:10 UTC
There is autocorrect feature. But where is no any guides or examples how to deal with source code changing (for example add imports, supertypes or something like this). Is it possible provide samples, links or guildes about code changing with detekt?

**Comment by cortinico** [comment] 2020-12-08 09:49
Probably a duplicate of https://github.com/detekt/detekt/issues/2314

We don't have documentation for this as there are no detekt rule that are using this feature (other than the one from KtLint). There are no official API to properly support editing the code on Detekt's end.

You can probably do as suggested in #2314: you can use the `rawReplaceWithText` function on `LeafPsiElement` to full replace a `PsiElement` with your custom text.

**Comment by BraisGabin** [comment] 2020-12-08 10:08
And probably ktlint code base could help you to see examples. All their rules have this feature.

**Comment by comdiv** [comment] 2020-12-08 10:17
thx

**Closed** 2020-12-08 10:18 UTC
Labels: support

**Comment by ln-12** [comment] 2024-03-25 16:07
Hey @comdiv, did you find a solution how to do this in detekt? I don't see how I can for example a `KtNamedFunction` or the `bodyExpression` to a `LeafPsiElement` as the cast will always fail.
