### ISSUE TITLE
Tasks `detektAndroidDebugUnitTest` `detektAndroidReleaseUnitTest` and `detektAndroidDebugAndroidTest` fail to run in a KMM project

### ISSUE THREAD

**Issue by mkrussel77** [detekt/detekt#3840] opened 2021-05-26 13:03 UTC
## Expected Behavior

Able to run these tasks and gradle will run

## Observed Behavior

An exception is thrown and no tasks are run

```
Could not determine the dependencies of task ':pangea-core:detektAndroidReleaseUnitTest'.
> Could not resolve all task dependencies for configuration ':pangea-core:releaseUnitTestCompileClasspath'.
   > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :pangea-core:
       - Configuration ':pangea-core:releaseApiElements' variant android-aidl declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
           - Unmatched attributes:
               - Provides attribute 'artifactType' with value 'android-aidl' but the consumer didn't ask for it
               - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
       - Configuration ':pangea-core:releaseApiElements' variant android-manifest declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
           - Unmatched attributes:
               - Provides attribute 'artifactType' with value 'android-manifest' but the consumer didn't ask for it
               - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
       - Configuration ':pangea-core:releaseApiElements' variant android-renderscript declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
           - Unmatched attributes:
               - Provides attribute 'artifactType' with value 'android-renderscript' but the consumer didn't ask for it
               - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
       - Configuration ':pangea-core:releaseApiElements' variant android-symbol-with-package-name declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
           - Unmatched attributes:
               - Provides attribute 'artifactType' with value 'android-symbol-with-package-name' but the consumer didn't ask for it
               - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'release' but the consumer didn't ask for it
```

## Context

Since these tasks are part of the check task, that task cannot be run.
This can be worked around by disabling the tasks.

The project has Kotlin targets for iOS, JVM, and Android.

```
kotlin {
    ios()
    jvm()
    android()
   
    more configuration
}
```

## Your Environment

* Version of detekt used: 1.16.0 and 1.71.2
* Version of Gradle used (if applicable): 6.7.1
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version: MacOS 11.3.1
* Link to your project (if it's a public repository):
* AGP 4.2.1

**Comment by cortinico** [comment] 2021-05-26 13:27
Can you please provide a reproducer? Like a smaller/empty project where we could check out what is going on? It's hard to troubleshoot this otherwise

> Version of Gradle used (if applicable): 6.7.1

Can you also try to bump to Gradle 7.x and verify if the issue is still happening?

**Comment by BraisGabin** [comment] 2021-05-26 13:41
`detektAndroidReleaseUnitTest` doesn't exist. It could be `detektReleaseAndroidTest` but it doesn't exist either. Android doesn't allow you tu run the android test in release, you only can run them in debug. You should run `detektDebugAndroidTest`.

You can run `./gradlew :yourModule:tasks | grep detekt` to see the valid tasks.

**Comment by mkrussel77** [comment] 2021-05-26 15:06
Run the `check` task on this project produces the config error.




[detekt-sample.zip](https://github.com/detekt/detekt/files/6547711/detekt-sample.zip)

**Comment by cortinico** [comment] 2021-05-26 16:15
I was able to reproduce (thanks for the sample project).
Sadly I could not come up with a solution, but it seems like with KMM, the `test` and `androidTest` build types fails to fallback to "debug" for the sake of configuration resolution.

I've cleaned your project and came up with a version that contains only the bare minimum detekt setup, but that it's still failing:

[detekt-sample-cleaned.zip](https://github.com/detekt/detekt/files/6548146/detekt-sample-cleaned.zip)

So far the issue seems to be really similar to https://github.com/apollographql/apollo-android/issues/2401. I've asked @martinbonnin some help, maybe he can give us some hint :)

Will keep on investigating in the next days.
If you do some findings, please post them here.

**Comment by mkrussel77** [comment] 2021-05-26 19:00
I've been unable to come up with a way to remove those tasks from the `check` task to allow updating.  Only thing that has worked is using the `-x` option on the command line, but I've not gotten anything to work in the build.gradle files.

**Comment by 3flex** [comment] 2021-05-27 00:02
To disable a detekt task in the build file you should be able to do something like:

```kotlin
tasks.detektAndroidReleaseUnitTest {
    enabled = false
}
```

**Comment by cortinico** [comment] 2021-05-27 11:08
> Edit: though if this problem comes up during configuration phase this might not help, apologies if so.

Nope the problem is not happening at configuration phase, but only when running the tasks.

**Comment by martinbonnin** [comment] 2021-05-27 14:38
I could make it work by adding this: 

```kotlin
val artifactType = Attribute.of("artifactType", String::class.java)

class DisambiguationRule: AttributeDisambiguationRule<String> {
    override fun execute(t: MultipleCandidatesDetails<String>) {
        /**
         * The default disambiguation rules exclude the jar variants because they define the `org.gradle.libraryelements`
         *
         * See https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/MultipleCandidateMatcher.java#L221
         *
         * Not 100% sure why this happens but forcing to use the jar in this specific case fixes the issue
         */
        val jar = t.candidateValues.firstOrNull { it == "jar" }
        if (jar != null) {
            t.closestMatch(jar)
        }
    }

}

dependencies.attributesSchema.attribute(artifactType).disambiguationRules.add(DisambiguationRule::class.java
```

I tried this after putting a breakpoint in the Gradle resolution code [on this line](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/MultipleCandidateMatcher.java#L234) but TBH, I'm not 100% sure if that's a good solution

State when the breakpoint is reached for the record:

![Screenshot 2021-05-27 at 16 33 33](https://user-images.githubusercontent.com/3974977/119845589-b065bb00-bf09-11eb-8c55-9437fc0f642b.png)

**Comment by mkrussel77** [comment] 2021-06-10 02:20
I tried to disable the task but I'm unable to do it.

When using `tasks.findByName` the task is not found, cannot find it when looping through the tasks either.  Tried to do it in an `afterEvaluate` block but the task still cannot be found.

I could find the task when added using `tasks.whenTaskAdded`, but disabling it there doesn't work.  The task still tries to resolve its dependencies and fails.

**Comment by StefanOltmann** [comment] 2021-06-10 04:46
Same here.  I have to exklude the tasks.

```
project.gradle.startParameter.excludedTaskNames.add('yourTaskName')
```

Overall it looks like that Detekt does not work (well) with Kotlin Native. I get a lot of false positives with "actual & expect".

I hope Detekt will support KMM soon.

**Comment by cortinico** [comment] 2021-06-10 11:29
> Overall it looks like that Detekt does not work (well) with Kotlin Native. I get a lot of false positives with "actual & expect".
> I hope Detekt will support KMM soon.

We do support Kotlin/Native & Kotlin Multiplatform.
Please open this as a separate issue as we can't fix it if we don't know what's the rule you're referring to.

**Comment by mkrussel77** [comment] 2021-06-10 12:20
The way I'm working around the issue is to disable all the Multiplatform detekt tasks.  This removes all the type resolving checks, but does let us keep upgrading until the Android bug here is fixed.

`detekt.multiplatform.disabled=true`

**Comment by eygraber** [comment] 2021-06-24 23:04
Is this something that needs to be addressed from the Android Gradle Plugin side of things?

**Comment by cortinico** [comment] 2021-07-01 12:37
> Is this something that needs to be addressed from the Android Gradle Plugin side of things?

Most probably yes. I believe is a misconfiguration of the classpath for the `androidTest` and `test` sourcesets. I wasn't able to find meaningful resources on this front.

I believe that as a "workaround" we could exclude the `androidTest` and `test` tasks for Android targets from the generation. Not elegant but it would make Detekt more KMP friendly.

Any help on this side is more than accepted 🙏

**Comment by eygraber** [comment] 2021-07-01 21:48
Could you file an issue at https://issuetracker.google.com/issues/new?component=192708&template=840533

**Comment by arkivanov** [comment] 2021-07-04 17:32
The following temporary workaround worked for me:
```
    gradle.startParameter.excludedTaskNames.addAll(
            "detektAndroidDebugAndroidTest",
            "detektAndroidDebugUnitTest",
            "detektAndroidReleaseUnitTest",
            "detektAndroidDebug",
            "detektAndroidRelease"
    )
```

**Comment by cortinico** [comment] 2021-07-05 08:58
Thanks for the workaround @arkivanov 👍 

Is there a reason why you're excluding also:

>             "detektAndroidDebug",
>             "detektAndroidRelease"

They should work correctly imho.

**Comment by arkivanov** [comment] 2021-07-05 09:04
@cortinico the last two tasks we failing with the same error, so I had to exclude them as well.

Also I could not update my KMP project to the latest version anyway, because looks the Type Resolution got broken. There were various compilation errors in the build logs and false positive signals from `UnusedImport` check. I will likely try again and file bug reports.

**Comment by cortinico** [comment] 2021-08-09 01:18
Thank you all for the support. It took me quite some time to debug/fix this, but I believe this will do the job: #4026.

I've updated the KMP detekt support to delegate to AGP for resolving classpath (as we're already doing for pure Android projects).

As a side note, I haven't really found what was the root cause of the failure to resolve the `releaseUnitTestCompileClasspath` due to attribute mismatch (I haven't found any relevant issue or discussion on any public forum).

**Closed** 2021-08-11 21:02 UTC
Labels: help wanted, gradle
