### ISSUE TITLE
New rule: ForbbidenInnerClass

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#2748] opened 2020-05-29 07:59 UTC
## Expected Behavior of the rule
ForbbidenInnerClass: It flags all the uses of the modifier `inner`.

## Context
The `inner` classes creates congnitive complexity. You are looking to a class that have access to the outer class so the dependencies are more blurry. And this leaves to antipatterns like the outer class retaining a class (for example a listener) so it's inner class can access it instead of provide it as a dependency itself.

**Comment by schalkms** [comment] 2020-05-29 20:53
I have a different opinion here. The `inner` was explicitly designed to use it. 

I agree with your statement that it creates a bit more cognitive complexity. If you overuse the inner class feature it gets complex, yes. Let's say for instance you use 7 inner classes inside 1 file. That could pose a problem. Per se I wouldn't say that `inner` classes are bad by design. Even detekt's codebase uses inner classes (~10x).

**Comment by schalkms** [comment] 2020-06-15 17:52
I’d also favor to close this, since the **ComplexClass** rule already handles the overuse of such things.

**Closed** 2020-06-15 17:54 UTC
Labels: discussion
