### ISSUE TITLE
Deprecate/Remove the `OptionalWhenBraces` rule (was: not possible to comply with `BracesOnWhenStatements`)

### ISSUE THREAD

**Issue by igorescodro** [detekt/detekt#6153] opened 2023-05-26 18:40 UTC
## Expected Behavior
When applying the rule `BracesOnWhenStatements`, the `OptionalWhenBraces` should be ignored. At the moment, it seems that both rules are conflicting.

## Observed Behavior

The following code is failing:
```kotlin
fun testWhen() {
    when (Random(100).nextInt()) {
        in 1..25 -> println("low")
        in 26..50 -> println("med")
        in 51..100 -> {
            println("high")
            throw IllegalAccessException("TOO HIGH")
        }
    }
}
```
```
style - 5min debt
	BracesOnWhenStatements - [Inconsistent braces, make sure all branches either have or don't have braces.] at TestRule.kt:9:9
```

However, the following code is also failing:
```kotlin
fun testWhen() {
    when (Random(100).nextInt()) {
        in 1..25 -> {
            println("low")
        }

        in 26..50 -> {
            println("med")
        }

        in 51..100 -> {
            println("high")
            throw IllegalAccessException("TOO HIGH")
        }
    }
}
```
```
style - 10min debt
	OptionalWhenBraces - [Optional braces in when expression detected.] at TestRule.kt:10:13
	OptionalWhenBraces - [Optional braces in when expression detected.] at TestRule.kt:14:13

```

## Context
If I correctly understand, one way of complying with this new rule is adding brackets for all the cases. Please, let me know if I'm doing something wrong here.

## Your Environment

* Version of detekt used: 1.23.0

**Comment by BraisGabin** [comment] 2023-05-27 08:09
We should deprecate `OptionalWhenBraces`. It's functionality is already implemented in the new rule.

(and because of 2.0 we could just remove it)

So, as workaround I recommend you to disable `OptionalWhenBraces`.

**Comment by cortinico** [comment] 2023-05-27 15:42
> We should deprecate `OptionalWhenBraces`

Should we just remove it on `main` and deprecate it in the `release/1.x` branch?

**Comment by BraisGabin** [comment] 2023-05-28 14:10
I'm not 100% sure if needed to port to `release/1.x`. But if someone port it, perfect.

**Comment by cortinico** [comment] 2023-07-25 18:11
> Is my understanding correct?

Yes correct, I've assigned this issue to you @mdemianova 
Can you do the deprecation first?

**Comment by mdemianova** [comment] 2023-07-25 18:43
> Can you do the deprecation first?

Sure!

**Comment by mdemianova** [comment] 2023-08-05 20:01
I see the issue is still open, does this task require something else to do?

**Comment by BraisGabin** [comment] 2023-08-06 11:21
No, nothing else. Thanks for the contributions!

**Closed by BraisGabin** 2023-08-06 11:22 UTC
Labels: bug, help wanted, rules, good first issue
