### ISSUE TITLE
Release tag doesn't match expected commit SHA using GitHub Action template

### ISSUE THREAD

**Issue by mjovanc** [detekt/detekt#5948] opened 2023-03-28 08:06 UTC
## Expected Behavior
Should be able to download the artifact with URL.

## Observed Behavior
During the "plugin" of GitHub Actions with Detekt it tries to use the version v1.55.0 and it fails on:

```
Run gh api graphql --field tagName=$DETEKT_RELEASE_TAG --raw-field query='
[31](https://github.com/kryptokrona/kryptokrona-api/actions/runs/4540643834/jobs/8001813262#step:3:32)
Release tag doesn't match expected commit SHA
[32](https://github.com/kryptokrona/kryptokrona-api/actions/runs/4540643834/jobs/8001813262#step:3:33)
Error: Process completed with exit code 1.
```

I also tried using v1.22.0-RC2 but same behaviour.

## Steps to Reproduce
1. Go to a repo and select actions
2. Press "New workflow
3. Search for Detekt and select Configure
4. Save it and it will not run due to the error I described above

## Context
Trying to run Static Code Analysis on my Kotlin/Ktor project.

## Your Environment
* Version of detekt used: 1.55.0 and 1.22.0-RC2
* Version of Gradle used (if applicable): 7.5.1
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/4klwxsv3i2nl6
* Operating System and version: macOS 13.2.1 (22D68)
* Link to your project (if it's a public repository): https://github.com/kryptokrona/kryptokrona-api

**Comment by 3flex** [comment] 2023-03-29 21:42
Sounds like a duplicate of https://github.com/detekt/detekt/issues/5228

Can you please confirm? If so, there doesn't seem to be anything we can do to fix it.

**Comment by cortinico** [comment] 2023-04-02 15:50
> Version of detekt used: 1.55.0 and 1.22.0-RC2

Also there is no Detetk 1.55

**Closed** 2023-04-24 12:51 UTC
Labels: bug, waiting for feedback
