### ISSUE TITLE
Task in apply from failed, but work from top level build.gradle file

### ISSUE THREAD

**Issue by mtrakal** [detekt/detekt#3594] opened 2021-03-22 20:51 UTC
Have code:
```
task detektProjectBaseline(type: io.gitlab.arturbosch.detekt.DetektCreateBaselineTask) {
    description = "Overrides current baseline."
    ignoreFailures.set(true)
    parallel.set(true)
    buildUponDefaultConfig.set(true)
    setSource(files(rootDir))
    config.setFrom(files("$rootDir/config/detekt/detekt.yml"))
    baseline.set(file("$rootDir/config/detekt/detekt-baseline.xml"))
    include("**/*.kt")
    include("**/*.kts")
    exclude("**/resources/**")
    exclude("**/build/**")
}
```
when this code is located in top level `build.gradle` file. Gradle sync and build work as expected. But when I just move it to external file and call `apply from 'file.gradle'` build failed on: 
> Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'io' for root project 'My Application' of type org.gradle.api.Project.

### Expected Behavior
Build work as expected

### Current Behavior
Build failed with error `Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'io' for root project 'My Application' of type org.gradle.api.Project.`

### Steps to Reproduce 
https://github.com/mtrakal/gradle-detekt-issue

https://github.com/mtrakal/gradle-detekt-issue/blob/master/config/detekt.gradle
https://github.com/mtrakal/gradle-detekt-issue/blob/master/build.gradle

I reported same issue to gradle, because have no idea where is the root of cause: https://github.com/gradle/gradle/issues/16613

**Comment by cortinico** [comment] 2021-03-22 22:24
Thanks for providing a reproducer.
It will work correctly if you add:

```groovy
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.16.0"
  }
}
```

on top of your `config/detekt.gradle`.

The reason is because that external script is failing to load Detekt classes inside the classpath (hence you need to specify it explicitly).

I'm closing it here, feel free to reopen if I haven't solved 👍

**Closed by cortinico** 2021-03-22 22:24 UTC

**Comment by mtrakal** [comment] 2021-03-24 09:10
Wow, thanks a lot, this solution work 👍 🥇
