### ISSUE TITLE
Excluding Sarif output report via yaml config file does not work

### ISSUE THREAD

**Issue by WebTiger89** [detekt/detekt#7588] opened 2024-08-28 13:36 UTC
Detekt gradle plugin v1.23.6
JVM 17
Kotlin 2.0.20

Excluding Sarif output report via yaml config file does not work:

```
output-reports:
  active: true
  exclude:
   - 'SarifOutputReport'
  # - 'TxtOutputReport'
   - 'XmlOutputReport'
   - 'HtmlOutputReport'
   - 'MdOutputReport'
```

This won't exclude it, but rather create a detekt.sarif file under build/reports/detekt. The content of the file is also weird (2384 lines)

**Comment by 3flex** [comment] 2024-08-28 14:03
Duplicate of https://github.com/detekt/detekt/issues/6464

Use 'sarif' until this is fixed in detekt 2 release.

> The content of the file is also weird

Please open a new issue for this with more details.

**Closed** 2024-08-28 14:03 UTC
Labels: bug
