### ISSUE TITLE
DetektMain doesn't work as expected in Android projects

### ISSUE THREAD

**Issue by BraisGabin** [detekt/detekt#4044] opened 2021-08-14 13:20 UTC
## Expected Behavior
If I run `:app:detektMain` in this project: https://github.com/BraisGabin/detekt-main-bug twice the second time the tasks `:app:detektDebug` and `:app:detektRelease` are not runned again because they are UP-TO-DATE.

## Observed Behavior
Plot twist: They are not UP-TO-DATE.

Other behaviour that I checked is that, when I run the task only the `release` or the `debug` reports are generated. But never both (If I keep running the task over and over both reports are created). And for sure there is a bug there:

![Captura de pantalla 2021-08-14 a las 15 10 47](https://user-images.githubusercontent.com/721244/129447364-dd7c9502-68e0-4f0a-bbbe-32929234cb92.png)

You can see in the scan (link below) that the release task is running because it thinks that its "output" should be the debug one.

If I run `./gradlew :app:detektDebug` or `./gradlew :app:detektRelease` all works as expected.

The same happens with `./gradlew :app:detektTest` BUT `:app:detektBaselineMain` and `:app:detektBaselineTest` work as expected.

## Steps to Reproduce
Execute `./gradlew :app:detektMain` twice

## Context
Maybe related with #4035

## Your Environment
* Version of detekt used: 1.18.0 and 1.17.1 (I didn't check other versions)
* Version of Gradle used (if applicable): 7.1.1 and 6.9
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/4mn62j6i5qrtm/timeline
* Operating System and version: MacOS
* Link to your project (if it's a public repository): https://github.com/BraisGabin/detekt-main-bug

**Comment by 3flex** [comment] 2021-08-16 12:26
This may be a dupe of #3926 and if so it should be fixed by https://github.com/detekt/detekt/pull/3687

**Comment by cortinico** [comment] 2021-08-17 08:42
> Other behaviour that I checked is that, when I run the task only the `release` or the `debug` reports are generated. But never both (If I keep running the task over and over both reports are created). And for sure there is a bug there:

Definitely the same issue of #3926, and as @3flex mentioned, it will be fixed by #3687
As a side note we should also make sure that we generate reports usign the task name as default (and not override each other).

**Closed** 2021-09-17 01:17 UTC
Labels: bug, gradle
