### ISSUE TITLE
Wrong offset: 5450. Should be in range: [0, 5438]

### ISSUE THREAD

**Issue by mrSan4o** [detekt/detekt#3496] opened 2021-02-23 18:16 UTC
I run 'detektBaseline' command on root path of my project. or run detektDevDebugBaseline on `app` module.
config of detekt gradle plugin:
```
detekt {
    input = files(
            "src/main/kotlin"
    )
    autoCorrect = getBooleanPropertyOrDefault("autoCorrect", false)
    buildUponDefaultConfig = false
    config = files("$rootDir/lint/detekt/detekt-default.yml", "$rootDir/lint/detekt/detekt-config.yml")
    baseline = file("lint/detekt/baseline.xml")
}
```

## Expected Behavior
Expect that file 'baseline.xml' will be created

## Observed Behavior
I got gradle exception
```
...app\src\main\kotlin\ru\sportmaster\android\mrm\expeditor\dagger\modules\additional\AdditionalOrderBindingsModule.kt led to an exception. 
  The original exception message was: Wrong offset: 5450. Should be in range: [0, 5438]
  Running detekt '1.16.0-RC1' on Java '1.8.0_171-b11' on OS 'Windows 10'
  If the exception message does not help, please feel free to create an issue on our GitHub page.
```
content of AdditionalOrderBindingsModule.kt :
```
package ru.sportmaster.android.mrm.expeditor.dagger.modules.additional

import androidx.lifecycle.ViewModel
import dagger.Binds
import dagger.Module
import dagger.android.ContributesAndroidInjector
import dagger.multibindings.IntoMap
import ru.sportmaster.android.mrm.expeditor.dagger.scopes.FragmentScope
import ru.sportmaster.android.mrm.expeditor.dagger.util.ViewModelKey
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.AdditionalOrderActivity
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.AdditionalOrderViewModel
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.AdditionalOrderForPaymentFragment
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.AdditionalOrderForPaymentResultActivity
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.AdditionalOrderForPaymentViewModel
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.card.AdditionalOrderCardPaymentFragment
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.card.AdditionalOrderCardPaymentViewModel
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.cash.AdditionalOrderCashPaymentActivity
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.cash.AdditionalOrderCashPaymentFragment
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.giftcard.GiftCardCancelReservationAdditionalOrderViewModel
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.history.AdditionalOrderPaymentsActivity
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.history.operation.AdditionalOrderPaymentCardCancelMposActivity
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.history.operation.AdditionalOrderPaymentCardCancelTerminalActivity
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.history.operation.AdditionalOrderPaymentOperationActivity
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.multi.AdditionalOrderMultiPaymentActivity
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.payment.multi.AdditionalOrderMultiPaymentViewModel
import ru.sportmaster.android.mrm.expeditor.ui.activity.orders.additional.services.SelectAdditionalOrderServicesActivity

@Module
interface AdditionalOrderBindingsModule {
    @Binds
    @IntoMap
    @ViewModelKey(AdditionalOrderViewModel::class)
    fun bindAdditionalOrderViewModel(viewModel: AdditionalOrderViewModel): ViewModel

    @ContributesAndroidInjector
    fun contributeAdditionalOrderActivity(): AdditionalOrderActivity

    @ContributesAndroidInjector
    fun contributeAdditionalOrderPaymentsActivity(): AdditionalOrderPaymentsActivity

    @ContributesAndroidInjector
    fun contributeSelectAdditionalOrderServicesActivity(): SelectAdditionalOrderServicesActivity

    @ContributesAndroidInjector
    fun contributeAdditionalOrderPaymentOperationActivity(): AdditionalOrderPaymentOperationActivity

    @ContributesAndroidInjector
    fun contributeAdditionalOrderPaymentCardCancelMposActivity(): AdditionalOrderPaymentCardCancelMposActivity

    @ContributesAndroidInjector
    fun contributeAdditionalOrderPaymentCardCancelTerminalActivity(): AdditionalOrderPaymentCardCancelTerminalActivity

    @ContributesAndroidInjector(modules = [AdditionalOrderForPaymentsResultActivityFragmentsModule::class])
    fun additionalOrderForPaymentResultActivityInjector(): AdditionalOrderForPaymentResultActivity

    @Binds
    @IntoMap
    @ViewModelKey(AdditionalOrderForPaymentViewModel::class)
    fun bindAdditionalOrderToPayViewModel(viewModel: AdditionalOrderForPaymentViewModel): ViewModel

    @Module
    interface AdditionalOrderForPaymentsResultActivityFragmentsModule {
        @FragmentScope
        @ContributesAndroidInjector
        fun additionalOrderForPaymentFragmentInjector(): AdditionalOrderForPaymentFragment
    }

    @ContributesAndroidInjector
    fun contributeAdditionalOrderCashPaymentActivityInjector(): AdditionalOrderCashPaymentActivity

    @Module
    interface AdditionalOrderMultiPaymentActivityBindingsModule {
        @ContributesAndroidInjector
        fun contributeAdditionalOrderCardPaymentFragmentInjector(): AdditionalOrderCardPaymentFragment

        @ContributesAndroidInjector
        fun contributeAdditionalOrderCashPaymentFragmentInjector(): AdditionalOrderCashPaymentFragment
    }

    @ContributesAndroidInjector(modules = [AdditionalOrderMultiPaymentActivityBindingsModule::class])
    fun contributeAdditionalOrderMultiPaymentActivityInjector(): AdditionalOrderMultiPaymentActivity

    @Binds
    @IntoMap
    @ViewModelKey(AdditionalOrderCardPaymentViewModel::class)
    fun bindAdditionalOrderCardPaymentViewModel(viewModel: AdditionalOrderCardPaymentViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(AdditionalOrderMultiPaymentViewModel::class)
    fun bindAdditionalOrderMultiPaymentViewModel(viewModel: AdditionalOrderMultiPaymentViewModel): ViewModel

    @Binds
    @IntoMap
    @ViewModelKey(GiftCardCancelReservationAdditionalOrderViewModel::class)
    fun bindGiftCardCancelReservationAdditionalOrderViewModel(viewModel: GiftCardCancelReservationAdditionalOrderViewModel): ViewModel
}

```

## Environment
Version of detekt used: 1.16.0-RC1
Version of Gradle used (if applicable): 4.1.1
Operating System and version: Windows 10

**Comment by cortinico** [comment] 2021-02-23 21:17
Seems like a duplicate of https://github.com/detekt/detekt/issues/2693

**Comment by chao2zhang** [comment] 2021-02-23 23:43
Please do try out 1.16.0-RC2. This version should include a patch fix for this type of issue.

**Comment by mrSan4o** [comment] 2021-02-24 07:16
Thanks chao2zhang. changing version to 1.16.0-RC2 helped

**Closed** 2021-02-24 08:17 UTC
Labels: duplicate
