### ISSUE TITLE
Baseline path works only for baseline generation

### ISSUE THREAD

**Issue by PawelDedio** [detekt/detekt#3985] opened 2021-07-28 06:11 UTC
## Expected Behavior
Baseline path set via `baseline =` in gradle should be respected in all detekt commands

## Observed Behavior
Custom baseline path or name is respected only in `detektBaseline` command. In `detekt` command, the default name and path is used instead.

## Steps to Reproduce

1. Open project
2. Run `./gradlew detekt` - detekt will fail
3. Rename `app/detekt-baseline-disabled.xml` to `app/detekt-baseline.xml` - detekt won't fail

## Context
In our project we use detekt-cli on CI, and gradle plugin for local run. We want to have just only one baseline placed inside `projectRoot/detekt` directory. For now only the default baseline works for gradle plugin. 

## Your Environment

* Version of detekt used: 1.18.0-RC2
* Version of Gradle used (if applicable): 6.5
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/c4x2l6r74x3kw
* Operating System and version: macOS Big Sur 11.5
* Link to your project (if it's a public repository): [Detektbug.zip](https://github.com/detekt/detekt/files/6890708/Detektbug.zip)

**Comment by chao2zhang** [comment] 2021-07-28 06:42
Hello @PawelDedio, thanks for the report.

It appears that 
- In your project, `detekt.gradle` need to have `baseline = file("$rootDir/detekt/baseline.xml")` so that it recognizes the top-level directory.
- It seems that you have `app/detekt-baseline.xml` in your repository, and that would actually take higher precendence than what's configured in the `detekt {}` extension. https://github.com/detekt/detekt/pull/2787#issuecomment-679964597

In general you should have a solution without waiting for changes in Detekt, but I am also curious why it is built that way.

**Comment by PawelDedio** [comment] 2021-07-28 07:10
Hi @chao2zhang,

Setting `baseline = file("$rootDir/detekt/baseline.xml")` changes nothing. In the current state of attached project, there is no `app/detekt-baseline` file and gradle setting points to `baseline.xml` inside `app` module (which is correct) and still detekt don't recognize it.

**Comment by chao2zhang** [comment] 2021-08-07 00:41
@PawelDedio Apologize for getting back to this late. I did some investigation and found that this is a regression introduced in https://github.com/detekt/detekt/pull/3429

```
            extension.baseline?.takeIf { it.exists() }?.let { baselineFile ->
                baseline.set(project.layout.file(project.provider { baselineFile }))
            }
```
In the code snippet above, `extension.baseline` will be resolved eagerly (it will be the default value we set in `DetektExtension` -> `.fileValue(File("detekt-baseline.xml"))`

```
          baseline.set(project.layout.file(project.provider { extension.baseline }))
```
If write the code this way, `extension.baseline` will be resolved correctly.

@BraisGabin I think we probably need to revert the change for the time being. In my opinion, the better way to tackle this is to define `baseline` as a `RegularFileProperty` and leverage convention.

**Comment by cortinico** [comment] 2021-08-07 11:09
> @BraisGabin I think we probably need to revert the change for the time being. In my opinion, the better way to tackle this is to define `baseline` as a `RegularFileProperty` and leverage convention.

Agree. Specifically leveraging `.convention` will also simplify the code a bit.

**Comment by BraisGabin** [comment] 2021-08-07 14:57
@PawelDedio thanks for the report and the repro project!

This is strange because I can't reproduce this issue in the project that I work for... but I can reproduce it perfectly in yours... And I have no idea what's the different part.

I'm ok about rolling this back but, could it be a breaking change?

> the better way to tackle this is to define `baseline` as a `RegularFileProperty` and leverage convention.

I don't know exactly what you mean with this. To be honest I don't understand the difference between `Detekt` and `DetektExtension` in the gradle plugin. And how those two are related.

**Comment by chao2zhang** [comment] 2021-08-07 18:42
`DetektExtension.baseline` is of type `File?`, I assume the type `RegularFileProperty`, such as returned by `objects.fileProperty()`, rhymes with Gradle's lazy computation.

Let me first reproduce this scenario with a Gradle Testkit integration test before making any further actions.

**Comment by chao2zhang** [comment] 2021-08-08 06:25
💡  @PawelDedio I found that we have this line
`tasks.detekt.jvmTarget = "1.8"` before `detekt {}` block in build.gradle. I think this causes the `Detekt` gradle task to be resolved eagerly (See more in https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview). This issue can be addressed by
- Move `tasks.detekt.jvmTarget = "1.8"` after the `detekt {}` block.
- Remove `tasks.detekt.jvmTarget = "1.8"`.
- Use Lazy configuration API (Although it seems that we need to refactor off script plugin apply `apply from: "$rootProjectDir/detekt/detekt.gradle"`).
   ```
   tasks.withType(io.gitlab.arturbosch.detekt.Detekt.class).configureEach {
        jvmTarget = "1.8"
    }
   ```

In the end, I think this is a great finding - We need to make sure that our Detekt documentation is using Task Configuration Avoidance API across the board.

**Comment by BraisGabin** [comment] 2021-08-08 07:39
That have sense, I didn't understand why I couldn't reproduce it in my project.

**Closed** 2021-08-09 20:22 UTC
Labels: gradle, documentation
