### ISSUE TITLE
Support JDK 11+

### ISSUE THREAD

**Issue by ZacSweers** [detekt/detekt#2892] opened 2020-07-25 02:12 UTC
Your feature request may already be reported!
Please search in the [issues](https://github.com/detekt/detekt/issues) before creating a new one.

## Expected Behavior
JDK 11 should work

## Current Behavior
It will not work due to use of `javax.xml.stream.XMLOutputFactory.newFactory()`. While JAXB artifacts exist separately for compatibility, these require quite a bit of extra work for use with the standalone CLI. Would be great if this project handled this better by either using a different XML parser or bundling those replacement dependencies directly.

Further context: https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis/48204154#48204154 

## Context
We're working on updating our repo to JDK 11+ and this project is not currently compatible

**Comment by ZacSweers** [comment] 2020-07-25 07:04
Here's a simple JDK 11+ compatible approach

```kotlin
import org.apache.commons.lang.StringEscapeUtils
import org.w3c.dom.Element
import org.w3c.dom.Node
import org.w3c.dom.NodeList
import java.io.BufferedWriter
import java.nio.file.Files
import java.nio.file.Path
import javax.xml.parsers.DocumentBuilderFactory

object Baselines {
  internal fun parse(path: Path): Baseline {
    val builderFactory = DocumentBuilderFactory.newInstance()
    val docBuilder = builderFactory.newDocumentBuilder()
    val doc = docBuilder.parse(Files.newInputStream(path).buffered())
    val element = doc.documentElement
    val manuallySuppressed = element.getSingleElementByTag("ManuallySuppressedIssues")
        .parseIdValues()
    val currentIssues = element.getSingleElementByTag("CurrentIssues")
        .parseIdValues()
    return Baseline(manuallySuppressed, currentIssues)
  }

  private fun Element.getSingleElementByTag(tagName: String): Element {
    return getElementsByTagName(tagName).asSequence().filterIsInstance<Element>().single()
  }

  private fun Element.parseIdValues(): Set<String> {
    return getElementsByTagName("ID")
        .asSequence()
        .mapTo(LinkedHashSet(), Node::getTextContent)
  }

  private fun NodeList.asSequence(): Sequence<Node> {
    return (0 until length).asSequence().map(::item)
  }
}

internal fun Baseline.writeTo(path: Path) {
  // There are fancy DOM writing APIs out there, but we don't need it here for this simple stuff.
  Files.newOutputStream(path).bufferedWriter().use { writer ->
    writer.apply {
      write("<?xml version=\"1.0\" ?>")
      newLine()
      write("<SmellBaseline>")
      newLine()
      manuallySuppressedIssues.writeTo(writer, "ManuallySuppressedIssues")
      newLine()
      currentIssues.writeTo(writer, "CurrentIssues")
      newLine()
      write("</SmellBaseline>")
      newLine()
    }
  }
}

private fun Set<String>.writeTo(writer: BufferedWriter, tag: String) {
  with(writer) {
    if (isEmpty()) {
      write("  <$tag/>")
    } else {
      write("  <$tag>")
      newLine()
      joinTo(writer, separator = "\n") {
        "    <ID>${StringEscapeUtils.escapeXml(it)}</ID>"
      }
      newLine()
      write("  </$tag>")
    }
  }
}
```

**Comment by arturbosch** [comment] 2020-07-26 19:47
Hi!
We are actively testing with jdk > 8 and I'm developing locally with JDK14 and can't reproduce this issue..
Do you have any documentation where and why `javax.xml.stream.XMLOutputFactory.newFactory()` should be deprecated/removed?
Afaik, jaxb got removed but not the streaming api which is not part of jaxb and is still present in JDK9+.

We had this issue some years ago with the removal of `IndentingXMLStreamWriter` but have our own implementation now.
For 2.0 I would like to remove XML from detekt and move to yaml (idk why I started with yaml for config but xml for baseline xD).

**Comment by ZacSweers** [comment] 2020-07-26 19:48
Hmm, I had to copy this code over since we merge all baselines manually and it doesn't compile on jdk 11+

**Comment by BraisGabin** [comment] 2020-10-25 20:12
I created this script but I can't reproduce your problem. I tried with the actual version and the last version when you opened this issue (1.9.1)

```shell
docker run --rm openjdk:11 bash -c "wget -P /usr/bin https://github.com/detekt/detekt/releases/download/v1.14.2/detekt && chmod +x /usr/bin/detekt && git clone https://github.com/detekt/detekt.git && cd detekt && detekt --baseline base.xml --create-baseline && detekt --baseline base.xml"
```

Could you modify my script to make the error appear?

**Comment by arturbosch** [comment] 2020-11-02 18:11
Closing as can't reproduce for now.

**Closed by arturbosch** 2020-11-02 18:11 UTC
Labels: invalid, support, waiting for verification
