### ISSUE TITLE
Detekt<VariantName> does not work run with type resolution

### ISSUE THREAD

**Issue by spasnoor21** [detekt/detekt#5527] opened 2022-11-11 18:13 UTC
Detekt<VariantName> does not work run with type resolution, nor does it generate the report.

## Expected Behavior

When I run ` ./gradlew tasks ` the tasks says `detekt<VariantName>Debug` should run with type resolution.

## Observed Behavior

When I run ` ./gradlew tasks ` the tasks says `detekt<VariantName>Debug` runs with type resolution, but it doesn't. 
## Your Environment

* Version of detekt used:
* Version of Gradle used (if applicable):
* Gradle scan link (add `--scan` option when running the gradle task):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by 3flex** [comment] 2022-11-11 21:59
Sorry to hear you're having trouble with detekt, but we'll need a lot more information to help you. It's essential to at least complete the "Steps to reproduce" section in the issue template.

**Comment by TWiStErRob** [comment] 2022-11-30 09:46
@spasnoor21 it doesn't have to be a full-on working project (although that's extremely preferred). It's possible that your Gradle Detekt setup or your yaml config contains something that breaks things. Have a look in your Gradle code (`detekt {`, `withType<...Detekt>`, `DetektExtension`, `detekt.yml`). Essentially anywhere `detekt` is mentioned in your project might be relevant.

**Comment by 3flex** [comment] 2022-12-27 08:00
Closing - it's been 6 weeks since feedback was requested. Please reopen if you have more information to share and we may be able to investigate, thanks!

**Closed by 3flex** 2022-12-27 08:00 UTC
Labels: bug, waiting for feedback
