### ISSUE TITLE
iOS type resolution targets do not work

### ISSUE THREAD

**Issue by mkrussel77** [detekt/detekt#4493] opened 2022-01-14 22:09 UTC
## Expected Behavior

I expect some report files in the build/reports/detekt folder for iOS
I expect warnings in the iOS source code to be printed to console  when running the iOS targets 

## Observed Behavior

The reports directory does not contain reports for the iOS targets.
If I just run the iOS target no warnings are printed

## Steps to Reproduce

In the attached project run
` ./gradlew detektIosX64Main`

## Context

My guess is that this is related to hierarchical platforms.  The grade script has the `ios`  platform and that generates the `iosX64` and `iosArm64`.

The issue means I cannot detect issues in the iOS source sets that require type resolution.

## Your Environment

* Version of detekt used: 1.19.0
* Version of Gradle used (if applicable): 7.0.2
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/f5fbtzbduflvm
* Operating System and version: Mac OS 11.6.1
* Link to your project (if it's a public repository):  Attached
[FooLibrary.zip](https://github.com/detekt/detekt/files/7873493/FooLibrary.zip)

**Comment by cortinico** [comment] 2022-01-14 22:14
> The issue means I cannot detect issues in the iOS source sets that require type resolution.

Closing as that's essentially the intended behavior. 

Type Resolution on KMP works only for Android & JVM targets.
iOS/Native/JS Targets supports syntactic-only inspection. 

I haven't found a way to make TR works for them and apparently the suggested solution (also by some JB engineers) is to move to compiler plugins. Therefore github.com/detekt/detekt-compiler-plugin/ might be your best bet 👍

**Closed by cortinico** 2022-01-14 22:14 UTC
Labels: bug
