### ISSUE TITLE
Regression: no longer allows JDK 19

### ISSUE THREAD

**Issue by Pr0methean** [detekt/detekt#5939] opened 2023-03-25 02:06 UTC
## Expected Behavior
`detekt` 1.22.0 is able to run on a JDK 19 project, just as `detekt` 1.21.0 was.

## Observed Behavior
```
Execution failed for task ':detekt'.
> Invalid value (19) passed to --jvm-target, must be one of [1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
```

## Steps to Reproduce
1. Check out https://github.com/Pr0methean/OcHd-KotlinBuild/commit/eb16b4d68c493aaf179a4c70f5e64a7b7aa9997a
2. Run `gradle detekt`
## Context
I've been using JDK 19 for this project since it reached GA, and Detekt never previously complained about it and was always able to find a variety of issues when they were present.

## Your Environment

* Version of detekt used: 1.22.0
* Version of Gradle used (if applicable): 8.0.2
* Gradle scan link (add `--scan` option when running the gradle task): https://scans.gradle.com/s/iumksj7qrgao4
* Operating System and version: Mac OS 13.2.1 & Ubuntu 20.04.5
* Link to your project (if it's a public repository): https://github.com/Pr0methean/OcHd-KotlinBuild

**Comment by 3flex** [comment] 2023-03-25 12:17
Duplicate of https://github.com/detekt/detekt/issues/5866

This will be fixed in the next release or you can use snapshots in the meantime.

**Closed** 2023-03-25 12:17 UTC
Labels: bug
