### ISSUE TITLE
Method signature in baseline changes when adding/removing a doc comment

### ISSUE THREAD

**Issue by roomscape** [detekt/detekt#4767] opened 2022-04-25 15:01 UTC
## Expected Behavior
- Given I have a method that exceeds the allowed method length or method complexity
- And I have suppressed the warning via my `baseline.xml`
- When I add a doc comment (`/** ... */`) to the method
- Then detekt should continue to pass

## Observed Behavior
After adding the doc comment, the suppression no longer works. Re-running `detektBaseline` shows that the signature has actually changed.

## Steps to Reproduce
See https://github.com/roomscape/detekt-baseline-issue, or:

- Create a long method in a class
- Run `detekt` and observe that it fails
- Run `detektBaseline`
- Run `detekt` and observe that it passes
- Add a doc comment to the long method
- Run `detekt` and observe that it fails
- Run `detektBaseline` and observe that the `baseline.xml` file has changed

Suppression for a method without a doc comment:
```xml
    <ID>LongMethod:Example.kt$Example$fun checkFoo()</ID>
```

Suppression for the same method after a doc comment is added:
```xml
    <ID>LongMethod:Example.kt$Example$ fun checkFoo()</ID>
```

## Context
- I tried to add a doc comment to an existing method in a large project
- I had to regenerate the detekt baseline in order to push my changes

## Your Environment
* Version of detekt used: 1.20.0
* Version of Gradle used (if applicable): 7.4
* Operating System and version: macOS 12.2.1

**Comment by cortinico** [comment] 2022-04-25 19:20
Yeah that's a bug. I think we tried to address it once with #4335 but that had to be reverted as it was causing problems.

**Comment by VitalyVPinchuk** [comment] 2022-06-21 14:52
It's unreproducible on the latest main.
Seems to be fixed.

**Comment by BraisGabin** [comment] 2022-06-21 16:55
Closing then, thanks!

**Closed** 2022-06-21 16:56 UTC
Labels: bug, help wanted
