### ISSUE TITLE
Docs: Programmatically update JSON schema URL

### ISSUE THREAD

**Issue by VictorIreri** [detekt/detekt#5894] opened 2023-03-12 07:54 UTC
## Context
The JSON schema URL, specified in [configurations.md](https://github.com/detekt/detekt/blob/main/website/docs/introduction/configurations.md?plain=1#LL182-L182C29), is now versioned. The docs were recently updated in https://github.com/detekt/detekt/pull/5881.

## Expected Behavior
The URL should be programmatically updated when a new version of detekt is being prepared as part of PRs like this https://github.com/detekt/detekt/pull/5544. This would reduce the chance of it being forgotten and becoming out of date.

However, it's worth bearing in mind that the schema itself is not automatically generated as specified here:
https://github.com/detekt/detekt/blob/f081ebe6f99d9069a3a7aa43e354c4aff4a7bc59/website/docs/introduction/configurations.md?plain=1#L191

## Current Behavior
The URL is manually updated.

**Comment by cortinico** [comment] 2023-03-15 00:23
Essentially a duplicate of #4162 if I'm not mistaken

**Comment by VictorIreri** [comment] 2023-03-15 03:08
Hey @cortinico! I think this issue is purely about updating the Schema Store URL in the docs programmatically when we release a new detekt version. The issue you linked however, is a much broader task to self-host the schema.

**Comment by cortinico** [comment] 2023-03-15 18:57
Yeah in general we need all the pipeline to generate & publish the json schema for each version

**Comment by schalkms** [comment] 2023-04-02 18:54
@cortinico shall we keep this (duplicated) issue open, then?
I'm doing a bit of housekeeping right now, hence the question.

**Comment by cortinico** [comment] 2023-04-03 12:35
> @cortinico shall we keep this (duplicated) issue open, then? I'm doing a bit of housekeeping right now, hence the question.

Nope we can close this. We'll keep #4162 to take care of all the JSON Schema related work

**Closed by cortinico** 2023-04-03 12:35 UTC
Labels: feature
