### ISSUE TITLE
[RFC] Suppress with new threshold

### ISSUE THREAD

**Issue by robstoll** [detekt/detekt#1224] opened 2018-10-10 08:17 UTC
It would be nice if one has the possibility to define a new threshold when one suppresses a certain issue. For instance. I might have a class which is larger than others which is fine but it should not get too big. 

The current approach would be to define two detekt tasks, exclude the class from one of them and define another threshhold in the other detekt task. That's not ideal for several reasons:
- lot of boilerplate (configuration wise) just for one class
- if we move the class around we have to adjust the filters of the two detekt tasks

Instead I would like to have something as follows:
```
SupressDetekt("LargeClass", threshold=200)
```
This way I get informed if the class gets bigger than I intended in a nice and clean way.

**Comment by Mauin** [comment] 2018-10-10 18:36
Interesting idea! This would definitely require a custom `@SupressDetekt` annotation to implement.

**Comment by robstoll** [comment] 2018-10-10 21:30
If you should add annotations then please provide it/them in a separate small jar so that it does not blow up the size off the real application. 
(As side note, it should be named `SuppressDetekt` => typo on my side).

**Comment by BraisGabin** [comment] 2021-07-25 09:06
We already deprecated `ThresholdRule` so I think that we don't want to implement this feature anymore because the "threashold" is treated as any other configuration. Closing. Please comment if you think that I'm missreading something.

**Closed by BraisGabin** 2021-07-25 09:06 UTC
Labels: core, feature

**Comment by robstoll** [comment] 2021-07-25 10:56
@BraisGabin I haven't used detekt for some time but I guess detekt has still a way to suppress a rule. Hence, it would still be nice to define a new limit in the annotation. Or how could this be achieved?

**Comment by BraisGabin** [comment] 2021-07-25 11:20
I was thinkign about this before closing this issue. It could have sense to have an annotation that allow you to "overwrite" the default values of a rule for a file. The problem is that it would create a lot of complexity for a low demand feature. If we see more demand we could rethink it but I think that for now we don't want to add something like this.
