### ISSUE TITLE
Baseline file option not compatible with multi module project

### ISSUE THREAD

**Issue by raymondboswel** [detekt/detekt#5712] opened 2023-01-20 07:17 UTC
## Expected Behavior
Setting the baseline file location should either merge all baseline files from subprojects, or documentation should make it clear that each subproject will overwrite the baseline file.

## Observed Behavior
Running ./gradlew detektBaselineMain in a multi module project results in a baseline file that clearly doesn't contain all the issues. After some head scratching and looking through existing issues the penny dropped that each module was overwriting the file.

I think adding a note in the docs should be a sufficient fix for this problem.

**Comment by BraisGabin** [comment] 2023-01-20 08:04
Could you create a PR making the documentation more clear to avoid future confusions?

We don't support an unified baseline out of the box. The idea is to have a baseline for each module.

**Comment by raymondboswel** [comment] 2023-01-20 08:09
Sure I'll give it a shot. What confused me, was that I set up detekt for our team about a year ago (with no updates in the mean time), and up till now it put everything in one big baseline file. We recently encountered a bug due to unreachable code, which made me realize that we weren't running in Type Resolution mode. After refactoring our config to enable TR, the baseline behaviour changed, though it could also just be the version update that changed the behaviour :shrug:

**Comment by BraisGabin** [comment] 2023-01-20 10:31
Oh! I see. TR creates even more baselines so maybe the issue is related with that.

**Comment by BraisGabin** [comment] 2023-03-04 00:05
Closing as there is nothing else to do here. If you still want to write that improvement for the documentation go ahead. We don't need this issue for that ;).

**Closed by BraisGabin** 2023-03-04 00:05 UTC
Labels: bug
